/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Controllers.AccountRegistry.DeserializeFile;
import static Controllers.AccountRegistry.file2;
import static Controllers.AccountRegistry.verifyAccount;
import Models.TransactionRecord;
import Controllers.TransactionList;
import static Controllers.SmartCardScanner.ScanTicket;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
//

/**
 *
 * @author piumi
 */
public class ExitGate extends javax.swing.JFrame {

    /**
     * Creates new form ExitGate
     */
    public ExitGate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        serialno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        accountid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("Account ID :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Scan Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 350, 120, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Serial No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 270, 90, 22);
        getContentPane().add(serialno);
        serialno.setBounds(430, 270, 174, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Account ID :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 160, 79, 20);

        accountid.setForeground(new java.awt.Color(255, 255, 255));
        accountid.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)));
        getContentPane().add(accountid);
        accountid.setBounds(660, 160, 56, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 120, 600, 370);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/P9.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 4, 900, 600);

        setSize(new java.awt.Dimension(751, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String SerialNo = serialno.getText();
        ScanTicket(SerialNo); // scan serial number
        verifyAccount(SerialNo); // verify the account
        TransactionList<TransactionRecord> recArr = null;       //declare accArr 
        recArr = new TransactionList<TransactionRecord>();         //create new accArr 
        recArr = (TransactionList<TransactionRecord>) DeserializeFile(file2);

        for (int i = 0; i < recArr.size(); i++) {
            TransactionRecord temp = (TransactionRecord) recArr.get(i);
            if (SerialNo.equals(temp.getSerialNo())) {

           // Stop_journey.accountbox.setText(String.valueOf(temp.getSerialNo()));
             JOptionPane.showMessageDialog(null, "Scanning Successfull!");
             this.dispose();
            }
        }
     
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
//}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitGate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitGate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitGate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitGate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitGate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel accountid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField serialno;
    // End of variables declaration//GEN-END:variables
}
