/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Controllers.DynamicJourney;
import static Controllers.DynamicJourney.deserialize;
import static Controllers.DynamicJourney.file1;
import Controllers.JourneyList;
import static Views.EntryGate_DynamicJourney.s2;
import static Controllers.DynamicJourney.checkjourneycomplete;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author DELL
 */
public class ExitGate_Stop_journey extends javax.swing.JFrame {

    /**
     * Creates new form Stop_journey
     */
    public ExitGate_Stop_journey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        STOP_JOURNEY_ = new javax.swing.JButton();
        s2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        STOP_JOURNEY_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        STOP_JOURNEY_.setText("CHECK DYNAMIC JOURNY EXISTS ");
        STOP_JOURNEY_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOP_JOURNEY_ActionPerformed(evt);
            }
        });
        getContentPane().add(STOP_JOURNEY_);
        STOP_JOURNEY_.setBounds(330, 280, 270, 80);

        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(s2);
        s2.setBounds(480, 310, 60, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Account ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 150, 70, 17);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(690, 140, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 130, 560, 360);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/P9.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 4, 950, 600);

        setSize(new java.awt.Dimension(920, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void STOP_JOURNEY_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOP_JOURNEY_ActionPerformed
        // TODO add your handling code here:
        try{
     // Check wether Dynamic Journey exits
        String destination = s2.getText();
        checkjourneycomplete(destination);
     
       JourneyList<DynamicJourney> joureny = null ;        //initialize journey
       joureny = JourneyList.getInstance();       //create new journey
       joureny = (JourneyList<DynamicJourney>) deserialize(file1);  //deserialize file
        
        for (int i = 0; i < joureny.size(); i++) {
            DynamicJourney temp = (DynamicJourney) joureny.get(i);
                if (destination.equals(temp.getDestination())) {
                    
                JOptionPane.showMessageDialog(null,  "Dynamic Journey Exists..\n"+" Do you want to add Destination?");
                EntryGate_DynamicJourney.s2.setText(String.valueOf(temp.getDestination()));
                } 
        }
        }catch(Exception e){
           e.printStackTrace();
           new ExitGate_AddDestination().setVisible(true);
           this.dispose();
       
    }//GEN-LAST:event_STOP_JOURNEY_ActionPerformed
    ExitGate_AddDestination.jTextField1.setText(this.jTextField1.getText());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Stop_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Stop_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Stop_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Stop_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitGate_Stop_journey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton STOP_JOURNEY_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel s2;
    // End of variables declaration//GEN-END:variables

  
}
