/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.Payment;
import Controllers.PaymentObjectList;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.UIManager;
/**
 *
 * @author DELL
 */
public class ExitGate_Payfor_DynamicJourney extends javax.swing.JFrame {

    /**
     *
     * @param paymentType
     * @param paymentAmount
     * @return
     */
    public Payment getPaymentMethod(String paymentType,String paymentAmount){
       if(paymentType == null){
         return null;
      }		
  
     if((paymentType.equals("Cash")))
 
     {
            new ExitGate_OpenExitGate().setVisible(true);
            this.dispose();
 
      } 
     else if((paymentType.equals("Card"))){
     
        }
        return null;

    }


    /**
     * Creates new form PayforDynamicJourney
     */
    public ExitGate_Payfor_DynamicJourney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        Payment_ = new javax.swing.JButton();
        pay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 170, 80, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 260, 297, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Amount");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 320, 110, 17);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));
        getContentPane().add(type);
        type.setBounds(460, 260, 90, 20);

        Payment_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Payment_.setText("Payment");
        Payment_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Payment_ActionPerformed(evt);
            }
        });
        getContentPane().add(Payment_);
        Payment_.setBounds(370, 390, 100, 25);

        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        getContentPane().add(pay);
        pay.setBounds(460, 320, 91, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRAVEL ANYWHERE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 190, 440, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 150, 460, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/P8.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 940, 630);

        setSize(new java.awt.Dimension(757, 543));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Payment_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Payment_ActionPerformed
        // TODO add your handling code here:
         String paymentType = type.getSelectedItem().toString();
        String paymentAmount=pay.getText();
        
        if(type.getSelectedItem()=="Cash")
        {   //if user select cash, then open Exit gate 
            new ExitGate_OpenExitGate().setVisible(true);
            this.dispose();
        }
        else if(type.getSelectedItem()=="Card"){
           //if user selcet card then next, user verify the card
           new ExitGate_VerifyCard().setVisible(true);
           this.dispose();
        }
        this.dispose();
        
        Payment usr = new Payment(paymentType,paymentAmount);
            
            PaymentObjectList <Payment> payArr = new PaymentObjectList<Payment>();
            PaymentObjectList <Payment> payArr2 = new PaymentObjectList<Payment>();
            payArr2 = deserialize(file1);
            
            payArr.add(usr);
      
            serialize(payArr);
    }//GEN-LAST:event_Payment_ActionPerformed

       PaymentObjectList <Payment> records = new PaymentObjectList <Payment>();

    /**
     *
     */
    public static final File file1 = new File("PaymentObject.txt");
        //serialize

    /**
     *
     * @param payArr
     */
       public void serialize(PaymentObjectList payArr){
        try{
          
           FileOutputStream fos = new FileOutputStream(file1);
           ObjectOutputStream oos = new ObjectOutputStream(fos);
           oos.writeObject(payArr);
           fos.close();
           System.out.println("Serialized");
        }
        catch(FileNotFoundException e){
            e.printStackTrace();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
      }
     //deserialize

    /**
     *
     * @param file1
     * @return
     */
      public PaymentObjectList deserialize(File file1){
        
         PaymentObjectList b_arraylist = null;
        try{
            FileInputStream fis = new FileInputStream(file1);
            ObjectInputStream ois = new ObjectInputStream(fis);
            b_arraylist = (PaymentObjectList)(PaymentObjectList)ois.readObject();
            fis.close();
            System.out.println("Deserialized");
            System.out.println(b_arraylist);
        }
            
        catch(FileNotFoundException e){
            e.printStackTrace();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } 
        catch(ClassCastException ex2){
            ex2.printStackTrace();
        }
        return b_arraylist;
    }
      
    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         new ExitGate_Discount().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Payfor_DynamicJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Payfor_DynamicJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Payfor_DynamicJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Payfor_DynamicJourney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitGate_Payfor_DynamicJourney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Payment_;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField pay;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
