/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Controllers.PaymentManager;
import Controllers.PaymentList;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author DELL
 */
public class ExitGate_Discount extends javax.swing.JFrame {
   
     PaymentList<PaymentManager> offers = new PaymentList<PaymentManager>();

    /**
     *
     */
    public static final File file = new File("Payment.txt");

    /**
     *
     * @param filename
     * @return
     */
    public static PaymentList Deserialize(File filename) {

        PaymentList d_arraylist = null;
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream ois = new ObjectInputStream(fis);

            d_arraylist = (PaymentList) ois.readObject();
            fis.close();
            System.out.println("Deserialized");
            System.out.println(d_arraylist);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        return d_arraylist;
    }
    /**
     * Creates new form Discount
     */
    public ExitGate_Discount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TOTAL_ = new javax.swing.JButton();
        offerbox = new javax.swing.JTextField();
        totalcost = new javax.swing.JTextField();
        costbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CONFIRM_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CHECK_OFFERS_ = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TOTAL_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TOTAL_.setText("Total Amount");
        TOTAL_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTAL_ActionPerformed(evt);
            }
        });
        getContentPane().add(TOTAL_);
        TOTAL_.setBounds(260, 300, 120, 25);

        offerbox.setText("2.8");
        offerbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                offerboxKeyTyped(evt);
            }
        });
        getContentPane().add(offerbox);
        offerbox.setBounds(460, 240, 113, 20);
        getContentPane().add(totalcost);
        totalcost.setBounds(460, 300, 113, 20);

        costbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costboxKeyTyped(evt);
            }
        });
        getContentPane().add(costbox);
        costbox.setBounds(460, 180, 113, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cost");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 180, 70, 20);

        CONFIRM_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CONFIRM_.setText("Confirm & Pay");
        CONFIRM_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRM_ActionPerformed(evt);
            }
        });
        getContentPane().add(CONFIRM_);
        CONFIRM_.setBounds(350, 370, 140, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 130, 70, 17);

        CHECK_OFFERS_.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CHECK_OFFERS_.setText("Check Offers");
        CHECK_OFFERS_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECK_OFFERS_ActionPerformed(evt);
            }
        });
        getContentPane().add(CHECK_OFFERS_);
        CHECK_OFFERS_.setBounds(260, 240, 120, 25);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(600, 130, 60, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 120, 480, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/P9.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 600);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Check Offers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 240, 120, 25);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("Check Offers");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(260, 240, 120, 25);

        setSize(new java.awt.Dimension(744, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TOTAL_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTAL_ActionPerformed
        // TODO add your handling code here:
      //calculate total
        
         double Cost,Offer;
         
           Cost=Double.parseDouble(costbox.getText());
            Offer=Double.parseDouble(offerbox.getText());
         
        if(Offer==0)
        {           
            totalcost.setText(""+Cost);
        }
        
        else{
         
            double c=Cost-Offer;
            totalcost.setText(""+c);
            
        }

    }//GEN-LAST:event_TOTAL_ActionPerformed

    private void CONFIRM_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRM_ActionPerformed
        // TODO add your handling code here:
        int x =JOptionPane.showConfirmDialog(null, "Did you check payment?");
        if(x==0){
       
        new ExitGate_Payfor_DynamicJourney().setVisible(true);
          ExitGate_Payfor_DynamicJourney.pay.setText(this.totalcost.getText());
        this.dispose();
        }else{
             new ExitGate_Discount().setVisible(true);
        this.dispose();
        }
       
 
    }//GEN-LAST:event_CONFIRM_ActionPerformed

    private void CHECK_OFFERS_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECK_OFFERS_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHECK_OFFERS_ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void costboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costboxKeyTyped
        // TODO add your handling code here:
         try {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_costboxKeyTyped

    private void offerboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_offerboxKeyTyped
        // TODO add your handling code here:
         try {
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_offerboxKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitGate_Discount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitGate_Discount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHECK_OFFERS_;
    private javax.swing.JButton CONFIRM_;
    private javax.swing.JButton TOTAL_;
    public static javax.swing.JTextField costbox;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField offerbox;
    public static javax.swing.JTextField totalcost;
    // End of variables declaration//GEN-END:variables
}
