/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Controllers.AccountRegistry.getAccountBalance;
import Controllers.PaymentManager;
import Controllers.RouteInformation;
import Controllers.PaymentList;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author piumi
 */
public class MobileApp_JourneySchedule extends javax.swing.JFrame {
    
    /**
     * Creates new form MobileApp_JourneySchedule
     */
    
      PaymentList<RouteInformation> schedule = new PaymentList<RouteInformation>();

    /**
     *
     */
    public static final File file = new File("Payment.txt");

    /**
     *
     * @param filename
     * @return
     */
    //deserialize payment list
    public PaymentList Deserialize(File filename) {

       PaymentList d_arraylist = null;
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream ois = new ObjectInputStream(fis);

            d_arraylist = (PaymentList) ois.readObject();
            fis.close();
            System.out.println("Deserialized");
           // System.out.println(d_arraylist);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        return d_arraylist;
    }                   

    /**
     *
     * @throws IOException
     */
    public MobileApp_JourneySchedule() throws IOException {
        initComponents();
      
        //display journey details on table
        
       RouteInformation RI =new RouteInformation();

       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    
     try {

    
        for(PaymentManager PM : RI.searchJourneys()){

      
      model.addRow(new Object [] {PM.setofoffers.source,PM.setofoffers.destination,PM.setofoffers.date,PM.setofoffers.time,PM.setofcosts.journeycost.transportType,PM.setofcosts.journeycost.cost}); 
      
        }
     
       } catch (IOException ex) {
            Logger.getLogger(MobileApp_JourneySchedule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MobileApp_JourneySchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    MobileApp_ReservationDetails jtRowData= new MobileApp_ReservationDetails();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        source = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        accountid = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Capture.PNG"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 3, 24)); // NOI18N
        jLabel1.setText("Journey Schedule");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        source.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manchester", "London", "Cambridge", " " }));
        source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceActionPerformed(evt);
            }
        });
        jPanel1.add(source, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 98, -1));

        destination.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bristol", "Leeds", "Sheffield", "Oxford", "Liverpool", " " }));
        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 98, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 23));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Source", "Destination", "Date", "Time", "Vehicle", "Cost"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 260, 174));

        jLabel4.setText("Account ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        accountid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(accountid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 30, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ka1 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(296, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          String current = source.getSelectedItem().toString();
          String dest = destination.getSelectedItem().toString();

          //filter details releavant to source and destination
           PaymentList<PaymentManager> journeyArr = null;
           journeyArr = new PaymentList<PaymentManager>();
           journeyArr = (PaymentList<PaymentManager>) Deserialize(file);
           
            try {
                boolean search = false;

                for (int i = 0; i < journeyArr.size(); i++) {
                    PaymentManager temp = (PaymentManager) journeyArr.get(i);
                    if ((source.getSelectedItem().equals(temp.getSource())) && (destination.getSelectedItem().equals(temp.getDestination()))) 

                   
                    {
                        search = true;
                     
                    }
                }
                if (search == true) {
                       
                TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(current));
                sorter.setRowFilter(RowFilter.regexFilter(dest));


                jTable1.setRowSorter(sorter);
        
         
                    }
                else {  JOptionPane.showMessageDialog(null, "Select correct destination");}
               
            } catch (NullPointerException exc) {
                exc.printStackTrace();
            }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        //set table values to next inteface
        
        
        int index=jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String source = model.getValueAt(index, 0).toString();
        String destination = model.getValueAt(index, 1).toString();
        String date = model.getValueAt(index, 2).toString();
        String time = model.getValueAt(index, 3).toString();
        String vehicle = model.getValueAt(index, 4).toString();
        String cost = model.getValueAt(index, 5).toString();
        String AccountID=accountid.getText();
        
       
        
//        String accountbalance=
        
        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jtRowData.source.setText(source);
        jtRowData.destination.setText(destination);
        jtRowData.date.setText(date);
        jtRowData.time.setText(time);
        jtRowData.vehicle.setText(vehicle);
        jtRowData.cost.setText(cost);
        
         MobileApp_ReservationDetails.accountid.setText(this.accountid.getText());
         
         getAccountBalance(AccountID);
         
        
        this.dispose();
        
      
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MobileApp_Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
          
      UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
    }
       
        catch(Exception e)
	{
            e.printStackTrace();
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MobileApp_JourneySchedule().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MobileApp_JourneySchedule.class.getName()).log(Level.SEVERE, null, ex);
                }

                }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel accountid;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> source;
    // End of variables declaration//GEN-END:variables
}
