/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Card;
//import static Controllers.Card.getTokenAccountID;
import Models.Cash;
import Controllers.Topup_Account;
import Controllers.Topup_AmountList;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.UIManager;


/**
 *
 * @author Kanchi
 */
public class TokenMachine_TopupAccount extends javax.swing.JFrame {

    /**
     *
     * @param paymentType
     * @param topup_amount
     * @return
     */
    public Topup_Account getPaymentMethod(String paymentType,String topup_amount){
       if(paymentType == null){
         return null;
      }		
  
     if((paymentType.equals("Cash")))
 
     {
      return new Cash(paymentType,topup_amount);
 
      } 
     else if((paymentType.equals("Card"))){
        return new Card(paymentType,topup_amount);
        }
        return null;

    }
    /**
     * Creates new form topUPAccountBalance
     */
    public TokenMachine_TopupAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.JComboBox<>();
        pay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        accountid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Card", "Cash" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type);
        type.setBounds(440, 260, 110, 30);
        getContentPane().add(pay);
        pay.setBounds(440, 320, 110, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Top Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 400, 90, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Account ID :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 160, 90, 17);

        accountid.setForeground(new java.awt.Color(255, 255, 255));
        accountid.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        getContentPane().add(accountid);
        accountid.setBounds(620, 160, 65, 23);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Top Up Account");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 190, 230, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Top Up Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 320, 110, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment Type");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 260, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 130, 590, 360);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/P8.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 900, 600);

        setSize(new java.awt.Dimension(917, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
        String AccountID = accountid.getText();         // TODO add your handling code here:
 
                
        String paymentType = type.getSelectedItem().toString();
        String topup_amount=pay.getText();
 
        //Factory Design Pattern
        if(type.getSelectedItem()=="Cash")
        {
           
            TokenMachine_TopupAccount paymentFactory = new TokenMachine_TopupAccount();
            
//          get an object of card and call its paymentMethod.

            Topup_Account cash=paymentFactory.getPaymentMethod(paymentType,topup_amount);
           
//          call issuccessfull method of card
         cash.IsSuccessfull();
         TokenMachine_CashPayment tokenMachine_CashPayment = new TokenMachine_CashPayment();
         tokenMachine_CashPayment.setVisible(true);
         tokenMachine_CashPayment.accountid.setText(AccountID);
         this.dispose();
            
        }
        
        else if(type.getSelectedItem()=="Card"){
         
                TokenMachine_TopupAccount paymentFactory = new TokenMachine_TopupAccount();

//     get an object of card and call its paymentMethod.
                
                Topup_Account card=paymentFactory.getPaymentMethod(paymentType,topup_amount);
      
      
//      call issuccessfull() method of card
        card.IsSuccessfull();
         TokenMachine_CardPayment tokenMachine_CardPayment = new TokenMachine_CardPayment();
         tokenMachine_CardPayment.setVisible(true);
         tokenMachine_CardPayment.accountid.setText(AccountID);
         this.dispose();
        
        }
    
        
         
            
        Topup_Account usr = new Topup_Account(paymentType,topup_amount);

        Topup_AmountList <Topup_Account> payArr = new Topup_AmountList<Topup_Account>();
        Topup_AmountList <Topup_Account> payArr2 = new Topup_AmountList<Topup_Account>();
        payArr2 = deserialize(file1);

        payArr.add(usr);

        serialize(payArr);

        }

        Topup_AmountList <Topup_Account> records = new Topup_AmountList <Topup_Account>();

        public static final File file1 = new File("Topup_Amount.txt");
        //
        public void serialize(Topup_AmountList payArr){
            try{

                FileOutputStream fos = new FileOutputStream(file1);
                ObjectOutputStream oos = new ObjectOutputStream(fos);

                oos.writeObject(payArr);
                fos.close();
                System.out.println("Serialized");
            }
            catch(FileNotFoundException e){
                e.printStackTrace();
            }
            catch (IOException e) {
                e.printStackTrace();
            }

        }

        public Topup_AmountList deserialize(File file1){

            Topup_AmountList b_arraylist = null;
            try{
                FileInputStream fis = new FileInputStream(file1);
                ObjectInputStream ois = new ObjectInputStream(fis);

                b_arraylist = (Topup_AmountList)(Topup_AmountList)ois.readObject();
                fis.close();
                System.out.println("Deserialized");
                System.out.println(b_arraylist);
            }

            catch(FileNotFoundException e){
                e.printStackTrace();
            }
            catch (IOException e) {
                e.printStackTrace();
            }
            catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
            catch(ClassCastException ex2){
                ex2.printStackTrace();
            }

            return b_arraylist;

    }//GEN-LAST:event_jButton1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TopupAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TopupAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TopupAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TopupAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokenMachine_TopupAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel accountid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField pay;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
