/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.Account;
import Controllers.Topup_Account;
import Controllers.AccountList;
import Controllers.Topup_AmountList;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kanchi
 */
public class TokenMachine_CardTransactionRecord extends javax.swing.JFrame {
      AccountList <Account> Record = new AccountList  <Account>();
      Topup_AmountList<Topup_Account> Topup_Amount = new Topup_AmountList<Topup_Account>();
    

    /**
     *
     */
    public static final File tfile = new File("Account.txt");

    /**
     *
     */
    public static final File tfile1 = new File("Topup_Amount.txt");

    /**
     *
     * @param filename
     * @return
     */
    public static AccountList Deserialize_T(File filename) {

        AccountList d_arraylist = null;
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream ois = new ObjectInputStream(fis);

            d_arraylist = (AccountList) ois.readObject();
            fis.close();
            System.out.println("Deserialized");
            System.out.println(d_arraylist);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        return d_arraylist;
    }

    /**
     *
     * @param filename
     * @return
     */
    public static Topup_AmountList Deserialize_Top(File filename) {

        Topup_AmountList top_arraylist = null;
        try {
            FileInputStream fis = new FileInputStream(filename);
            ObjectInputStream ois = new ObjectInputStream(fis);

            top_arraylist = (Topup_AmountList) ois.readObject();
            fis.close();
            System.out.println("Deserialized");
            System.out.println(top_arraylist);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }

        return top_arraylist;
    }
     
//
//    /**
//     *
//     */


    /**
     *
     * @param filename
     * @return
     */
                    

    /**
     * Creates new form Transaction_Record
     */
    public TokenMachine_CardTransactionRecord() {
        initComponents();
        
        //display system date
        Date d = new Date();
        String amPm = new SimpleDateFormat("aa").format(d);
        
        showdate();
        
        }
     void showdate(){
        
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        date.setText(s.format(d));
      
        
        //display transaction records on table
        

      
    }
    

        
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cuamount = new javax.swing.JTextField();
        accountbal = new javax.swing.JTextField();
        topupamount = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accountid = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ttable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Top Up Account");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 280, 130, 22);
        jPanel1.add(cn);
        cn.setBounds(210, 120, 144, 20);
        jPanel1.add(date);
        date.setBounds(209, 168, 144, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(53, 223, 0, 0);
        jPanel1.add(cuamount);
        cuamount.setBounds(209, 222, 144, 20);

        accountbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountbalActionPerformed(evt);
            }
        });
        jPanel1.add(accountbal);
        accountbal.setBounds(130, 390, 120, 20);

        topupamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topupamountActionPerformed(evt);
            }
        });
        jPanel1.add(topupamount);
        topupamount.setBounds(209, 286, 144, 20);

        b1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b1.setText("Account Balance");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(120, 430, 138, 31);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Transaction Record");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 30, 410, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Account ID :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(710, 40, 90, 17);

        accountid.setForeground(new java.awt.Color(255, 255, 255));
        accountid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(accountid);
        accountid.setBounds(800, 40, 65, 23);

        Ttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Current Amount", "Account Balance", "Date"
            }
        ));
        jScrollPane1.setViewportView(Ttable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(450, 160, 452, 323);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 120, 110, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 170, 110, 22);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current Amount");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 220, 130, 22);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 40, 90, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-1, -1, 970, 570);

        setSize(new java.awt.Dimension(971, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void accountbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountbalActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed

          String currentamnt = cuamount.getText();
          String accountbalance = accountbal.getText();
        
        double x,y;
        
         x=Double.parseDouble(cuamount.getText());
         y=Double.parseDouble(topupamount.getText());
        
         if(y==0)
        {           
            accountbal.setText(""+x);
        }
        
        else{
         
            double z=x+y;
            accountbal.setText(""+z);
            
        }
         
         
        
              
         
         
        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void topupamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topupamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topupamountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TokenMachine_Login().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokenMachine_TransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       try{
             UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
         }
         catch(Exception e){
             e.printStackTrace();
         }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new TokenMachine_TransactionRecord().setVisible(true);
                
                }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ttable;
    private javax.swing.JTextField accountbal;
    public static javax.swing.JLabel accountid;
    private javax.swing.JButton b1;
    public static javax.swing.JTextField cn;
    public static javax.swing.JTextField cuamount;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField topupamount;
    // End of variables declaration//GEN-END:variables
}
